spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/login
            - Path=/users/register
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/wallet/**
        - id: payment-api-service
          uri: lb://payment-api-service
          predicates:
            - Path=/payments/transfer